project_id = "ohvddptghpcrenxdpyxm"

[functions.manage-users]
verify_jwt = false

[functions.notion-isp-profile]
verify_jwt = false

[functions.crm-api]
verify_jwt = false

[functions.webhook-chamados]
verify_jwt = false
